logger:
  endpoints:
    - endpoint:
        type: "logging"
        name: "RemoteLog"
        class: "LogMessage"
        topic: "/RemoteLog"
        QoS: 10

YUKON_COMM_CONFIG:
  active_monitoring:
    period: 1.0
  board:
    - property:
        type: "data"
        name: "board_feedback"
        topic: "YUKON/BOARD/FEEDBACK"
        QoS: 10
    - property:
        type: "data"
        name: "Voltage_in"
        topic: "YUKON/Vin"
        QoS: 10
  modules:
    - module:
        type: "BigMotor"
        name: "BigMotor_M1"
        feedbacks:
          - feedback:
            name: "feedback"
            topic: "YUKON/MOTOR1/FEEDBACK"
            QoS: 10
    - module:
        type: "SerialServo"
        name: "SerialServo_S1"
        feedbacks:
          - feedback:
            name: "feedback"
            topic: "YUKON/SERVO1/FEEDBACK"
            QoS: 10



mqtt_broker: "192.168.1.101"
mqtt_port: 1883

logging:
  level: "DEBUG"
  file: "logs/yukon.log"
