


class SERIAL_CONFIG:
    YK_DEFAULT_BAUD = 115200
    YK_DEFAULT_PORT = "COM5"


class UDP_CONFIG:
    YK_UDP_IN_PORT = 5000

class MQTT_CONFIG:
    YK_MQTT_BROKER = "localhost"
    YK_MQTT_PORT = 1883

class YUKON_BOARD:
    YK_LED_A = "LED_A"
    YK_LED_B = "LED_B"
class YUKON_BOARD_TOPICS:
    TOPIC_ENABLE_MAIN_OUTPUT = "YUKON/ENABLE_MAIN_OUTPUT"
    TOPIC_LEDA = "YUKON/LED_A"
    TOPIC_LEDB = "YUKON/LED_B"

class MOTOR_TOPICS:
    TOPIC_MOTOR_ENABLE = "YUKON/*/ENABLE"
    TOPIC_MOTOR_SPEED = "YUKON/*/SPEED"

class SERVO_TOPICS:
    TOPIC_SERVO_ANGLE = "YUKON/*/ANGLE"