
class general_messages:
    TOPIC_MAIN_OUTPUT = "YUKON/ENABLE_MAIN_OUTPUT"
    TOPIC_LED_A_BLINK = "YUKON/LED_A_BLINK"
    TOPIC_LED_B_BLINK = "YUKON/LED_B_BLINK"

class motor1_messages:
    TOPIC_MOTOR_ENABLE = "YUKON/MOTOR1/ENABLE"
    TOPIC_MOTOR_SPEED = "YUKON/MOTOR1/SPEED"

class motor2_messages:
    TOPIC_MOTOR_ENABLE = "YUKON/MOTOR2/ENABLE"
    TOPIC_MOTOR_SPEED = "YUKON/MOTOR2/SPEED"