
class general_messages:
    TOPIC_MAIN_OUTPUT = "YUKON/ENABLE_MAIN_OUTPUT"
    TOPIC_LED_A_BLINK = "YUKON/LED_A_BLINK"
    TOPIC_LED_B_BLINK = "YUKON/LED_B_BLINK"
    TOPIC_ACTION = "YUKON/ACTION"

class motor1_messages:
    TOPIC_MOTOR_ENABLE = "YUKON/MOTOR1/ENABLE"
    TOPIC_MOTOR_SPEED = "YUKON/MOTOR1/SPEED"

class motor2_messages:
    TOPIC_MOTOR_ENABLE = "YUKON/MOTOR2/ENABLE"
    TOPIC_MOTOR_SPEED = "YUKON/MOTOR2/SPEED"

class servo1_messages:
    TOPIC_SERVO_ANGLE = "YUKON/SERVO1/ANGLE"


class feedback_messages:
    TOPIC_MOTOR1_FEEDBACK_REQ = "YUKON/MOTOR1/REQ/FEEDBACK"
    TOPIC_MOTOR1_FEEDBACK = "YUKON/MOTOR1/FEEDBACK"
    TOPIC_SERVO1_FEEDBACK_REQ = "YUKON/SERVO1/REQ/FEEDBACK"
    TOPIC_SERVO_FEEDBACK = "YUKON/SERVO1/FEEDBACK"
    TOPIC_BOARD_FEEDBACK = "YUKON/BOARD/FEEDBACK"