class actions:
    ACTION_BLINK_A = "BLINK_A"
    ACTION_BLINK_B = "BLINK_B"
    ACTION_OUTPUT_ENABLE = "OUTPUT_ENABLE"

    ACTION_MOTOR_ENABLE = "MOTOR_ENABLE"
    ACTION_MOTOR_SET_SPEED = "MOTOR_SET_SPEED"

    ACTION_SERVO_SET_ANGLE = "SERVO_SET_ANGLE"
